dockerを導入
nuita/nuita pull request #247
Opened 2020-09-13 17:32 UTC by ahis1503

### 変えたもの
  - bundleのインストール先にvendor/bundleを指定
    - プロジェクトディレクトリに入れることでホスト側と共有してキャッシュさせるため
  - 依存ツールのバージョンの変更
    - Node.js, yarnはバージョンが不明なので最新安定版に、mysqlはdockerレジストリから取ってくるため8系の最新に
  - docker外からアクセスするためにrailsが起動するデフォルトのホストを0.0.0.0にした

### 開発方法
  - VSCode Remote Developmentを使う方法（おすすめ）
    - VSCodeに[Remote Containers https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers]拡張機能をインストールする
    - プロジェクトを開いて、右下に出てくるポップアップのReopen in Containerボタンをクリック
      - またはコマンドパレットからRemote-Containers: Reopen in Containerを選択
    - 環境構築が自動で行われるのでしばらく待つ
      - nuita[/ bundleとnuita]node_modulesボリュームに予めコピーしておけばインストールが早くなるかも
    - VSCodeのターミナルからRailsを起動する
      - bundle installとyarn installは済んでるので、データベースのセットアップからやつ
        - $ rails db:setup
      - 予めnuita_databaseボリュームにコピーしておけば省略できるはず
      - $ rails s
  - 自力でやる方法
    - `docker-compose up -d`でコンテナを起動する
    - `docker-compose exec app bash`でコンテナに入る
      - ボリュームに関しては上と同じ
      - `bundle install && yarn install --check-files`
      - `rails db:setup`
      - `rails s`
    - `docker-compose down`でコンテナを終了する

2020-09-14 14:03 UTC, kypkyp requested changes
手元の環境で試してみましたが、問題なく動いてそうです！ :tada:

Rails本体への変更ですが、オプションで実行時に指定するやり方でDockerなしの環境でも動くようにできるかもしれません。
Dockerなしの状況を想定する必要ある？というのは微妙な問題ですが、少しの変更で動くと思うのでどうでしょうか？ 🙏 🙏 🙏

（あと本番のDocker化がまだ済んでないという問題もあります……本当はちゃんと時間をとって移行作業すべきなのですが、すみません）

2020-09-14 14:03 UTC, kypkyp commented on config/puma.rb
> +port        ENV.fetch("PORT") { 3000 }, "0.0.0.0"
これをRails本体で指定すべきかは少し迷いますね……。

「Dockerから開発するときは `rails s -b 0.0.0.0` ってしてね！」って書いて、puma.rb自体で指定するのは避けるべきな気もします。

2020-09-14 14:04 UTC, kypkyp commented on config/database.yml
> +  host: <%= ENV.fetch("MYSQL_HOST", "db") %>
ごめんなさい、送信してから気づいたのですが、指定してる項目が違うので上のコードのままだと動かないですね。別の案を考えてみます。

2020-09-14 20:53 UTC, ahis1503 commented on config/puma.rb
> +port        ENV.fetch("PORT") { 3000 }, "0.0.0.0"
それなら環境変数から指定するようにするのはどうですかね
docker内ではオプションを省略できるようにした上で、通常は今までと同じ動作にできるはずです

```suggestion
port        ENV.fetch("PORT") { 3000 }, ENV["HOST"]
```

2020-09-14 21:56 UTC, ahis1503 commented on config/database.yml
> +  host: <%= ENV.fetch("MYSQL_HOST", "db") %>
UNIXソケットとTCP/IPを使っての接続方法には[ほとんど違いはないらしい](https://serverfault.com/questions/466155/when-to-use-a-mysql-socket-and-when-to-use-a-hostport)ので、hostでの接続で統一してしまうのが簡単かもしれないです
たぶんデフォルトでlocalhostを指定しておけば接続できるかな

2020-09-16 14:58 UTC, kypkyp commented on config/database.yml
> +  host: <%= ENV.fetch("MYSQL_HOST", "db") %>
```suggestion
  host: <%= ENV.fetch("MYSQL_HOST", "db") {"localhost"} %>
```
これで動くの確認できました！感謝

2020-09-16 15:37 UTC, kypkyp commented on config/puma.rb
> +port        ENV.fetch("PORT") { 3000 }, "0.0.0.0"
動くの確認できました！

2020-09-16 15:50 UTC, kypkyp commented on config/database.yml
> +  host: <%= ENV.fetch("MYSQL_HOST", "db") %>
何度も申し訳ないけど意味的にはこっちのほうがよさそうですね
```suggestion
  host: <%= ENV.fetch("MYSQL_HOST", "localhost") %>
```

2020-09-16 15:51 UTC, kypkyp commented
Suggested ChangeでDocker外で動くようになるのを確認したので、あとはDockerfileに環境変数を追加すれば完成ですかね……？

2020-09-17 15:21 UTC, kypkyp approved these changes
👍 👍 👍

2020-09-17 15:21 UTC, merged